# https://blog.dcycle.com/blog/2022-03-25/php-apache-different-containers/
FROM nginx:alpine

COPY docker-resources/nginx/default.conf /etc/nginx/conf.d/
RUN sed -i 's/drupal_source:9000/drupal_destination:9000/g' /etc/nginx/conf.d/default.conf
COPY --from=dcycle/drupal:9php8-fpm-alpine /var/www/html /var/www/html
